language: cpp
dist: bionic
os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get -y install cmake llvm-8-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-10
    - g++-10

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DLLVM_DIR=/usr/lib/llvm-8/cmake
  - make
